### ISSUE TITLE
Missing emissions variables in detailed industry model version

### ISSUE THREAD

**Issue by gunnar-pik** [pik-piam/remind#82]
It seems several variables got lost in the reporting for the detailed industry version. Specifically, I am missing
"Emi|CO2|Industry|Direct" 
"Emi|CO2|Carbon Capture and Storage|Biomass|Energy|Demand|Industry" 
Emi|CO2|Energy|Supply|Gross

There might be more. 
@0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q [Michaja]

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
@gunnar-pik tl;dr: 
- `Emi|CO2|Carbon Capture and Storage|Biomass|Energy|Demand|Industry` and `Emi|CO2|Energy|Supply|Gross` seem fixed (83b2c8e)
-  `Emi|CO2|Industry|Direct` is gone at least a year and should be replaced by `Emi|CO2|Industry|Direct|BeforeTradBiomassCorr`.

-----

I'm still convinced that the disappearance of `Emi|CO2|Industry|Direct` is not recent.  When the package was moved to Github a year ago, the variable wasn't there: https://github.com/pik-piam/remind/blob/e2d31af0deeee6baa8cfe3c7a1f095292e1c9a30/R/reportEmi.R#L810-L839

This leaves the original change from `Emi|CO2|Industry|Direct` to `Emi|CO2|Industry|Direct|BeforeTradBiomassCorr`.
https://redmine.pik-potsdam.de/projects/mo/repository/revisions/13501/diff/remind/R/reportEmi.R 

That (`Emi|CO2|Industry|Direct|BeforeTradBiomassCorr`, and the other variables apparently) was missing due to another bug (83b2c8e), where Industry CCS numbers were `NA` instead of zero.

There is a [discussion about the differences](https://redmine.pik-potsdam.de/issues/2399) between `Emi|CO2|Industry|Direct|FromGamsCalculation` and `Emi|CO2|Industry|Direct|BeforeTradBiomassCorr`.  It remains largely true, but `Emi|CO2|Industry|Direct|FromGamsCalculation` seems too large by a factor of two (#83).  Will investigate.
